### ISSUE TITLE
how to get variable $_GET['authorized']

### ISSUE THREAD

**Issue by rimoi** [djchen/pocket-api-php#5]
in your example how get your variable `$_GET['authorized']` ?

**Comment by djchen** [comment]
Its part of the callback uri that Pocket redirects you back to:
https://github.com/djchen/pocket-api-php/blob/master/sample.php#L86

**Comment by rimoi** [comment]
Thank you for your availability.
By the way I am new to the use of pocket and since there is no documentation available on your package I will have 2 questions:

- How to get `accessToken` from the `consumerKey`?
- How to get the `tag_name` in result ?
Example : 
```
$options = [
        'tag' => 'label_test',
        'detailType' => 'complete'
        ];
$pocket = new \Pocket([
            'consumerKey' => $this->parameterBag->get('pocket_consumer_key'),
            'accessToken' => $this->parameterBag->get('pocket_token_key'),
        ]);
$list = $pocket->retrieve($options);
```
![capture d ecran de 2019-02-15 16-11-44](https://user-images.githubusercontent.com/14994150/52865239-760ef000-313c-11e9-9286-703d05c20ecc.png)

in the result I do not see the tag list for example in my case here `label_test`

**Information about my application :** 
I want to create a cron that goes all night recuquering pocket items and integrate it into my database My application runs on symfony 4.2


thank you

**Comment by djchen** [comment]
You already have the access token in the sample.php:
https://github.com/djchen/pocket-api-php/blob/master/sample.php#L41

You'll want to consult the Pocket API docs for that:
https://getpocket.com/developer/docs/v3/retrieve
(hint, you need detailType complete)
